import type { AppDatabase } from '../index.js';
import { media } from '../schema/index.js';

export function seedMedia(db: AppDatabase, adminId: number) {
  const now = new Date().toISOString();

  const records: (typeof media.$inferInsert)[] = [
    {
      filename: 'campus-main.jpg',
      originalName: 'campus-main.jpg',
      mimeType: 'image/jpeg',
      size: 524288,
      width: 1920,
      height: 1080,
      altText: 'Aerial view of main campus quad',
      title: 'Main Campus',
      path: 'uploads/campus-main.jpg',
      variants: { thumb: 'uploads/campus-main-thumb.jpg', medium: 'uploads/campus-main-md.jpg' },
      metadata: { camera: 'DJI Mavic 3', taken: '2025-08-15' },
      createdAt: now,
      createdBy: adminId,
    },
    {
      filename: 'campus-library.jpg',
      originalName: 'campus-library.jpg',
      mimeType: 'image/jpeg',
      size: 389120,
      width: 1600,
      height: 1067,
      altText: 'Students studying in the library reading room',
      title: 'Library Interior',
      path: 'uploads/campus-library.jpg',
      variants: { thumb: 'uploads/campus-library-thumb.jpg', medium: 'uploads/campus-library-md.jpg' },
      metadata: {},
      createdAt: now,
      createdBy: adminId,
    },
    {
      filename: 'campus-science-lab.jpg',
      originalName: 'campus-science-lab.jpg',
      mimeType: 'image/jpeg',
      size: 412672,
      width: 1600,
      height: 1200,
      altText: 'Modern science lab with students conducting experiments',
      title: 'Science Lab',
      path: 'uploads/campus-science-lab.jpg',
      variants: { thumb: 'uploads/campus-science-lab-thumb.jpg' },
      metadata: {},
      createdAt: now,
      createdBy: adminId,
    },
    {
      filename: 'college-logo.png',
      originalName: 'college-logo.png',
      mimeType: 'image/png',
      size: 45056,
      width: 400,
      height: 120,
      altText: 'Spacely College official logo',
      title: 'College Logo',
      path: 'uploads/college-logo.png',
      variants: {},
      metadata: { transparent: true },
      createdAt: now,
      createdBy: adminId,
    },
    {
      filename: 'campus-student-life.jpg',
      originalName: 'campus-student-life.jpg',
      mimeType: 'image/jpeg',
      size: 471040,
      width: 1920,
      height: 1280,
      altText: 'Students gathered on the campus lawn during fall festival',
      title: 'Student Life',
      path: 'uploads/campus-student-life.jpg',
      variants: { thumb: 'uploads/campus-student-life-thumb.jpg', medium: 'uploads/campus-student-life-md.jpg' },
      metadata: {},
      createdAt: now,
      createdBy: adminId,
    },
    {
      filename: 'campus-aerial.jpg',
      originalName: 'campus-aerial-2025.jpg',
      mimeType: 'image/jpeg',
      size: 614400,
      width: 2400,
      height: 1600,
      altText: 'Bird\'s eye view of entire campus grounds',
      title: 'Campus Aerial',
      path: 'uploads/campus-aerial.jpg',
      variants: { thumb: 'uploads/campus-aerial-thumb.jpg', medium: 'uploads/campus-aerial-md.jpg' },
      metadata: { camera: 'DJI Mavic 3', taken: '2025-09-01' },
      createdAt: now,
      createdBy: adminId,
    },
  ];

  const inserted = db.insert(media).values(records).returning().all();
  console.log(`  Seeded ${inserted.length} media record(s)`);
  return inserted;
}
